### ISSUE TITLE
add verification to get methods for sftp and ftp

### ISSUE THREAD

**Issue by mreinigjr** [q6-enterprises-inc/fluture-remote-file-manager#23]
When interacting with remote systems, there is always the concern that the data being retrieved is outdated or incomplete.  In terms of incomplete, this is particularly a concern when it comes to remote file downloads and a download is initiated while the provider is pushing an update.  In terms of outdated data, this happens when files are not updated at the expected frequency by the data provider.  All of these can be easily prevented by a proactive consumer.  To incorporate these features into this library we need to

- Integrate this functionality into the current "get" methods for at least
  - [x] ftp
  - [x] sftp
- [x] Outdated information will be determined by the timestamp provided by the provider.  Care may need to be taken to account for time zones.
  - [x] The comparison timestamp will be provided by the user.
- [x] Incomplete information will need to **at least** look at the change in bytes of the requested file over a short period of time, ~200 ms.  Another option here (suggested by @johngoza) is to take a hash of the entire file listing provided by remote server and compare that over the short period of time.  This will incur additional compute time, but would work all the same **assuming** the byte data is provided in the full file listing.

**Comment by johngoza** [comment]
Timezones will certainly be an issue. I suspect that all ftp/sftp we access will list file times in zulu (utc) but we'll need to confirm that. FRFM will not do any time conversion logic other than parsing so the impetus will be on the consumer

**Comment by mreinigjr** [comment]
Well, as long as the timestamp is formatted correctly, we should be able to convert with ease. The moment.js will do this with ease.  We should convert all timestamps to utc, then compare.  What do you think @johngoza?

**Comment by johngoza** [comment]
100%

**Comment by johngoza** [comment]
crap I didn't do the timestamp verification

**Comment by johngoza** [comment]
I've migrated the timestamp verification to issue #29 . It's separate work from the file validation so I feel okay about this

**Comment by johngoza** [comment]
This issue was closed with the merge of #28 . Separate issue was created for the time filtering work
